name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
   
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      with:
        vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer' 
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Restore NuGet packages
      run: nuget restore SampleWebApplication.sln
    
    - name: Build the Solution
      run: msbuild SampleWebApplication.sln /p:Configuration=Release
    
